import type { Meta, StoryObj } from '@storybook/react';
import { http, HttpResponse } from 'msw';
import { IndexPage } from './index';

const meta: Meta<typeof IndexPage> = {
  title: 'Pages/index',
  component: IndexPage,
  parameters: {
    msw: {
      handlers: [
        http.get('https://api.themoviedb.org/3/movie/popular', () => {
          return HttpResponse.json({
            page: 1,
            results: [
              {
                adult: false,
                backdrop_path: '/xlkclSE4aq7r3JsFIJRgs21zUew.jpg',
                genre_ids: [27, 53],
                id: 1034541,
                original_language: 'en',
                original_title: 'Terrifier 3',
                overview:
                  "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
                popularity: 6336.348,
                poster_path: '/63xYQj1BwRFielxsBDXvHIJyXVm.jpg',
                release_date: '2024-10-09',
                title: 'Terrifier 3',
                video: false,
                vote_average: 7.329,
                vote_count: 497,
              },
              {
                adult: false,
                backdrop_path: '/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg',
                genre_ids: [878, 28, 12],
                id: 912649,
                original_language: 'en',
                original_title: 'Venom: The Last Dance',
                overview:
                  "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
                popularity: 5956.639,
                poster_path: '/k42Owka8v91trK1qMYwCQCNwJKr.jpg',
                release_date: '2024-10-22',
                title: 'Venom: The Last Dance',
                video: false,
                vote_average: 6.669,
                vote_count: 412,
              },
              {
                adult: false,
                backdrop_path: '/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg',
                genre_ids: [16, 878, 10751],
                id: 1184918,
                original_language: 'en',
                original_title: 'The Wild Robot',
                overview:
                  "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
                popularity: 4774.796,
                poster_path: '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
                release_date: '2024-09-12',
                title: 'The Wild Robot',
                video: false,
                vote_average: 8.545,
                vote_count: 2240,
              },
              {
                adult: false,
                backdrop_path: '/jlWk4J1sV1EHgkjhvsN7EdzGvOx.jpg',
                genre_ids: [18, 27, 878],
                id: 933260,
                original_language: 'en',
                original_title: 'The Substance',
                overview:
                  'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
                popularity: 3232.213,
                poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
                release_date: '2024-09-07',
                title: 'The Substance',
                video: false,
                vote_average: 7.3,
                vote_count: 1227,
              },
              {
                adult: false,
                backdrop_path: '/oPUOpnl3pqD8wuidjfUn17mO1yA.jpg',
                genre_ids: [16, 878, 12, 10751, 28],
                id: 698687,
                original_language: 'en',
                original_title: 'Transformers One',
                overview:
                  'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.',
                popularity: 2919.953,
                poster_path: '/iHPIBzrjJHbXeY9y7VVbEVNt7LW.jpg',
                release_date: '2024-09-11',
                title: 'Transformers One',
                video: false,
                vote_average: 8.1,
                vote_count: 496,
              },
              {
                adult: false,
                backdrop_path: '/uGmYqxh8flqkudioyFtD7IJSHxK.jpg',
                genre_ids: [18, 80, 53],
                id: 889737,
                original_language: 'en',
                original_title: 'Joker: Folie à Deux',
                overview:
                  "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
                popularity: 2961.521,
                poster_path: '/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg',
                release_date: '2024-10-01',
                title: 'Joker: Folie à Deux',
                video: false,
                vote_average: 5.7,
                vote_count: 1248,
              },
              {
                adult: false,
                backdrop_path: '/6vn6K9oX82i6E86ZiHVxqVEMQqP.jpg',
                genre_ids: [878, 27],
                id: 945961,
                original_language: 'en',
                original_title: 'Alien: Romulus',
                overview:
                  'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
                popularity: 2067.258,
                poster_path: '/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
                release_date: '2024-08-13',
                title: 'Alien: Romulus',
                video: false,
                vote_average: 7.3,
                vote_count: 2084,
              },
              {
                adult: false,
                backdrop_path: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
                genre_ids: [878, 28],
                id: 335983,
                original_language: 'en',
                original_title: 'Venom',
                overview:
                  'Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.',
                popularity: 2018.088,
                poster_path: '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
                release_date: '2018-09-28',
                title: 'Venom',
                video: false,
                vote_average: 6.8,
                vote_count: 15849,
              },
              {
                adult: false,
                backdrop_path: '/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
                genre_ids: [28, 35, 878],
                id: 533535,
                original_language: 'en',
                original_title: 'Deadpool \u0026 Wolverine',
                overview:
                  'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
                popularity: 1724.744,
                poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
                release_date: '2024-07-24',
                title: 'Deadpool \u0026 Wolverine',
                video: false,
                vote_average: 7.705,
                vote_count: 4976,
              },
              {
                adult: false,
                backdrop_path: '/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg',
                genre_ids: [878, 28, 12],
                id: 580489,
                original_language: 'en',
                original_title: 'Venom: Let There Be Carnage',
                overview:
                  'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
                popularity: 1619.971,
                poster_path: '/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg',
                release_date: '2021-09-30',
                title: 'Venom: Let There Be Carnage',
                video: false,
                vote_average: 6.799,
                vote_count: 10081,
              },
              {
                adult: false,
                backdrop_path: '/9msuazXGWAyl7vhxVFU7e7Bb5Ik.jpg',
                genre_ids: [18, 10749],
                id: 179387,
                original_language: 'tl',
                original_title: 'Heavenly Touch',
                overview:
                  'Jonard is having trouble making ends meet. His mother is suffering from depression, and he and his sister are forced to quit school in order to take care of her. One day, Jonard meets up his friend Rodel, and Rodel introduces him to the world of massage parlors. Rodel teaches him massage, and brings him to Heavenly Touch, a syndicate-run massage parlor that mostly caters to homosexuals.',
                popularity: 1587.866,
                poster_path: '/ory8WuAqznTE7lfopTSymHpop2t.jpg',
                release_date: '2009-05-12',
                title: 'Heavenly Touch',
                video: false,
                vote_average: 6.31,
                vote_count: 21,
              },
              {
                adult: false,
                backdrop_path: '/csQSGH0QU8D3Ov5YLEYuHep8ihA.jpg',
                genre_ids: [53, 12, 28, 878],
                id: 1196470,
                original_language: 'fr',
                original_title: 'Survivre',
                overview:
                  'A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.',
                popularity: 1244.036,
                poster_path: '/7fR3KxswtY8OHHZuOUB9td58CRX.jpg',
                release_date: '2024-06-19',
                title: 'Survive',
                video: false,
                vote_average: 4.8,
                vote_count: 34,
              },
              {
                adult: false,
                backdrop_path: '/naNXYdBzTEb1KwOdi1RbBkM9Zv1.jpg',
                genre_ids: [27, 53],
                id: 420634,
                original_language: 'en',
                original_title: 'Terrifier',
                overview:
                  'A maniacal clown named Art terrorizes three young women on Halloween night and everyone else who stands in his way.',
                popularity: 1321.117,
                poster_path: '/sFaPj5UyIAsiRuIgVl60pCYUzmR.jpg',
                release_date: '2018-01-25',
                title: 'Terrifier',
                video: false,
                vote_average: 6.393,
                vote_count: 2322,
              },
              {
                adult: false,
                backdrop_path: '/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg',
                genre_ids: [16, 10751, 12, 35, 18],
                id: 1022789,
                original_language: 'en',
                original_title: 'Inside Out 2',
                overview:
                  "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
                popularity: 1613.815,
                poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
                release_date: '2024-06-11',
                title: 'Inside Out 2',
                video: false,
                vote_average: 7.613,
                vote_count: 4566,
              },
              {
                adult: false,
                backdrop_path: '/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg',
                genre_ids: [16, 10751, 35, 28],
                id: 519182,
                original_language: 'en',
                original_title: 'Despicable Me 4',
                overview:
                  'Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
                popularity: 1339.916,
                poster_path: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
                release_date: '2024-06-20',
                title: 'Despicable Me 4',
                video: false,
                vote_average: 7.111,
                vote_count: 2095,
              },
              {
                adult: false,
                backdrop_path: '/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
                genre_ids: [10751, 16, 10402, 12],
                id: 354912,
                original_language: 'en',
                original_title: 'Coco',
                overview:
                  "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.",
                popularity: 1558.152,
                poster_path: '/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
                release_date: '2017-10-27',
                title: 'Coco',
                video: false,
                vote_average: 8.2,
                vote_count: 19373,
              },
              {
                adult: false,
                backdrop_path: '/begseNUKhZcc05Bc1UggaX5GeES.jpg',
                genre_ids: [28, 53, 80],
                id: 976734,
                original_language: 'en',
                original_title: 'Canary Black',
                overview:
                  'Top level CIA agent Avery Graves is blackmailed by terrorists into betraying her own country to save her kidnapped husband. Cut off from her team, she turns to her underworld contacts to survive and help locate the coveted intelligence that the kidnappers want.',
                popularity: 1005.325,
                poster_path: '/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg',
                release_date: '2024-10-10',
                title: 'Canary Black',
                video: false,
                vote_average: 6.5,
                vote_count: 148,
              },
              {
                adult: false,
                backdrop_path: '/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg',
                genre_ids: [35, 14, 27],
                id: 917496,
                original_language: 'en',
                original_title: 'Beetlejuice Beetlejuice',
                overview:
                  "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
                popularity: 1091.039,
                poster_path: '/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg',
                release_date: '2024-09-04',
                title: 'Beetlejuice Beetlejuice',
                video: false,
                vote_average: 7.163,
                vote_count: 1684,
              },
              {
                adult: false,
                backdrop_path: '/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg',
                genre_ids: [27, 53],
                id: 663712,
                original_language: 'en',
                original_title: 'Terrifier 2',
                overview:
                  "A year after the Miles County massacre, Art the Clown is resurrected by a sinister entity. Art returns home, where he must hunt down and destroy teenage Sienna and her younger brother Jonathan on Halloween. As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
                popularity: 1087.967,
                poster_path: '/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg',
                release_date: '2022-10-06',
                title: 'Terrifier 2',
                video: false,
                vote_average: 6.766,
                vote_count: 1939,
              },
              {
                adult: false,
                backdrop_path: '/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg',
                genre_ids: [10749, 18],
                id: 1079091,
                original_language: 'en',
                original_title: 'It Ends with Us',
                overview:
                  "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
                popularity: 1305.752,
                poster_path: '/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg',
                release_date: '2024-08-07',
                title: 'It Ends with Us',
                video: false,
                vote_average: 7.197,
                vote_count: 955,
              },
            ],
            total_pages: 46911,
            total_results: 938208,
          });
        }),
        http.get('https://api.themoviedb.org/3/person/popular', () => {
          return HttpResponse.json({
            page: 1,
            results: [
              {
                adult: false,
                gender: 2,
                id: 64,
                known_for_department: 'Acting',
                name: 'Gary Oldman',
                original_name: 'Gary Oldman',
                popularity: 197.533,
                profile_path: '/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg',
                known_for: [
                  {
                    backdrop_path: '/y2DB71C4nyIdMrANijz8mzvQtk6.jpg',
                    id: 49026,
                    title: 'The Dark Knight Rises',
                    original_title: 'The Dark Knight Rises',
                    overview:
                      "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                    poster_path: '/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 80, 18, 53],
                    popularity: 88.504,
                    release_date: '2012-07-17',
                    video: false,
                    vote_average: 7.8,
                    vote_count: 22604,
                  },
                  {
                    backdrop_path: '/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg',
                    id: 155,
                    title: 'The Dark Knight',
                    original_title: 'The Dark Knight',
                    overview:
                      'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
                    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [18, 28, 80, 53],
                    popularity: 156.311,
                    release_date: '2008-07-16',
                    video: false,
                    vote_average: 8.515,
                    vote_count: 32791,
                  },
                  {
                    backdrop_path: '/tyBkBHKDrJyVUeCs550kMr61jnq.jpg',
                    id: 6114,
                    title: "Bram Stoker's Dracula",
                    original_title: "Bram Stoker's Dracula",
                    overview:
                      'In 19th century England, Count Dracula travels to London and meets Mina Harker, a young woman who appears as the reincarnation of his lost love.',
                    poster_path: '/scFDS0U5uYAjcVTyjNc7GmcZw1q.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [10749, 27],
                    popularity: 55.605,
                    release_date: '1992-11-13',
                    video: false,
                    vote_average: 7.5,
                    vote_count: 5067,
                  },
                ],
              },
              {
                adult: false,
                gender: 2,
                id: 1907997,
                known_for_department: 'Acting',
                name: 'Min Do-yoon',
                original_name: '민도윤',
                popularity: 188.491,
                profile_path: '/bHHn3krbHyxQIWb4JbHkPlV6Uu1.jpg',
                known_for: [
                  {
                    backdrop_path: null,
                    id: 865463,
                    title: "24 Year Old Yoon Yul's Sexy Breasts",
                    original_title: '24살윤율의섹시한젖가슴',
                    overview:
                      'Rookie actor Yunyul! Although she looks innocent, her secret private life is revealed in detail.  Sexy glamor rookie actor Yunyul’s breathtaking talk begins! Yunyul, who has a beautiful model body line and a bursting breast, but with a face that combines soft innocence and contradictory charm!  It boasts a voluptuous, powerful hardware since its debut early and came to the hottest Newcomer together many fans successfully her first interview with the film anchakhan the debut of receive the love of 2020  from an episode from the debut course she speaks to date Her anti-war charm, honestly revealing her usual dating course with the opposite sex she dreamed of! The honest interview of 24-year-old Yunyul begins.',
                    poster_path: '/qvGkjlLjTy1nxClxpw2BiUS6jHB.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'ko',
                    genre_ids: [18, 10749],
                    popularity: 30.582,
                    release_date: '2021-03-01',
                    video: false,
                    vote_average: 7.2,
                    vote_count: 18,
                  },
                  {
                    backdrop_path: null,
                    id: 721187,
                    title: 'Beauty Salon: Special Service 4',
                    original_title: '미용실 : 특별한 서비스 4',
                    overview:
                      'Focusing on the relationship between men and women in a beauty salon, Dae-hye, the director of a korean erotic film beauty salon, becomes more difficult to sell in a depression. The building owner’s rent pressure also comes in, and employee Juhee suggests to Dae-hye to do a bikini service, saying that a bikini beauty salon has hit the jackpot in a foreign country. Surprisingly, bikini service is on the jackpot and guests are increasingly looking for a more powerful service.',
                    poster_path: '/nJpoe1CKuiqh90qUliO6qHCeNYI.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'ko',
                    genre_ids: [10749],
                    popularity: 1.844,
                    release_date: '2022-12-01',
                    video: false,
                    vote_average: 6.4,
                    vote_count: 11,
                  },
                  {
                    backdrop_path: '/4yABbmwq7D0vsSmDVzpJbQdFGJW.jpg',
                    id: 643274,
                    title: 'Beauty Salon: Special Service 3',
                    original_title: '미용실 : 특별한 서비스 3',
                    overview:
                      "In a deserted salon, female hair designer Se-jeong quits, and the salon is at risk. Jeong-soo, the owner, takes measures to overcome this hardship! He hires special male designers with 'special services'. Lonely women in the neighborhood soon hear about this, and start swarming into the salon.",
                    poster_path: '/fMksaQrIVsFlVCLS8KQfLGZ5vgt.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'ko',
                    genre_ids: [10749],
                    popularity: 5.319,
                    release_date: '2019-04-29',
                    video: false,
                    vote_average: 5.3,
                    vote_count: 10,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 1452953,
                known_for_department: 'Acting',
                name: 'Alexa Blair Robertson',
                original_name: 'Alexa Blair Robertson',
                popularity: 167.412,
                profile_path: null,
                known_for: [
                  {
                    backdrop_path: '/dT48bnZP1HVNUjiOEfThNzq4qlZ.jpg',
                    id: 417830,
                    title: 'Diary of a Wimpy Kid: The Long Haul',
                    original_title: 'Diary of a Wimpy Kid: The Long Haul',
                    overview:
                      "A Heffley family road trip to attend Meemaw's 90th birthday party goes hilariously off course thanks to Greg's newest scheme to get to a video gaming convention.",
                    poster_path: '/mSBUClLuB70a2unFvW4m48OG9VF.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [35, 10751],
                    popularity: 23.935,
                    release_date: '2017-05-19',
                    video: false,
                    vote_average: 5.3,
                    vote_count: 470,
                  },
                  {
                    backdrop_path: '/xlkclSE4aq7r3JsFIJRgs21zUew.jpg',
                    id: 1034541,
                    title: 'Terrifier 3',
                    original_title: 'Terrifier 3',
                    overview:
                      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
                    poster_path: '/63xYQj1BwRFielxsBDXvHIJyXVm.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [27, 53],
                    popularity: 6336.348,
                    release_date: '2024-10-09',
                    video: false,
                    vote_average: 7.321,
                    vote_count: 500,
                  },
                  {
                    backdrop_path: '/NvVOmAdAvSrtbeshCr3T534Wfw.jpg',
                    id: 204784,
                    title: 'Anna Nicole',
                    original_title: 'Anna Nicole',
                    overview:
                      "Voluptuous beauty Anna Nicole Smith marries an elderly millionaire and poses for Playboy, but after her husband's death, her excessive drinking, pill-popping and weight fluctuations take their toll.",
                    poster_path: '/bUiaTH6HUac25MNWSXVf0XlAeq2.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [18],
                    popularity: 0.268,
                    release_date: '2013-06-29',
                    video: false,
                    vote_average: 5.0,
                    vote_count: 46,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 1392137,
                known_for_department: 'Acting',
                name: 'Margaret Qualley',
                original_name: 'Margaret Qualley',
                popularity: 158.418,
                profile_path: '/jStNyMj3acpLuH48awLVLqqlyaV.jpg',
                known_for: [
                  {
                    backdrop_path: '/xwgBHC2FgoIrQitl8jZwXXdsR9u.jpg',
                    id: 466272,
                    title: 'Once Upon a Time... in Hollywood',
                    original_title: 'Once Upon a Time... in Hollywood',
                    overview:
                      'Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…',
                    poster_path: '/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [35, 18, 53],
                    popularity: 56.311,
                    release_date: '2019-07-24',
                    video: false,
                    vote_average: 7.439,
                    vote_count: 13337,
                  },
                  {
                    backdrop_path: '/oLp6ueqQXNWvWCFwrb6tXDnH0Ye.jpg',
                    id: 290250,
                    title: 'The Nice Guys',
                    original_title: 'The Nice Guys',
                    overview:
                      'A private eye investigates the apparent suicide of a fading porn star in 1970s Los Angeles and uncovers a conspiracy.',
                    poster_path: '/clq4So9spa9cXk3MZy2iMdqkxP2.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [35, 80, 28],
                    popularity: 34.511,
                    release_date: '2016-05-15',
                    video: false,
                    vote_average: 7.12,
                    vote_count: 7849,
                  },
                  {
                    backdrop_path: '/tirhxzSR6g1A9Iayo2lpYW4luUF.jpg',
                    id: 433249,
                    title: 'IO',
                    original_title: 'IO',
                    overview:
                      "As a young scientist searches for a way to save a dying Earth, she finds a connection with a man who's racing to catch the last shuttle off the planet.",
                    poster_path: '/utH781EwjzzXQC6fZUO3cw8L5Ht.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [878],
                    popularity: 14.54,
                    release_date: '2019-01-18',
                    video: false,
                    vote_average: 4.952,
                    vote_count: 1348,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 115440,
                known_for_department: 'Acting',
                name: 'Sydney Sweeney',
                original_name: 'Sydney Sweeney',
                popularity: 154.466,
                profile_path: '/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg',
                known_for: [
                  {
                    backdrop_path: '/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg',
                    id: 85552,
                    name: 'Euphoria',
                    original_name: 'Euphoria',
                    overview:
                      'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
                    poster_path: '/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [18],
                    popularity: 279.858,
                    first_air_date: '2019-06-16',
                    vote_average: 8.311,
                    vote_count: 9724,
                    origin_country: ['US'],
                  },
                  {
                    backdrop_path: '/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg',
                    id: 1072790,
                    title: 'Anyone But You',
                    original_title: 'Anyone But You',
                    overview:
                      'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
                    poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [10749, 35],
                    popularity: 133.279,
                    release_date: '2023-12-21',
                    video: false,
                    vote_average: 7.0,
                    vote_count: 2141,
                  },
                  {
                    backdrop_path: '/6bGmHzPEq2n6g17moqWwDpJBEom.jpg',
                    id: 1041613,
                    title: 'Immaculate',
                    original_title: 'Immaculate',
                    overview:
                      'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.',
                    poster_path: '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [27, 9648, 53],
                    popularity: 101.691,
                    release_date: '2024-03-20',
                    video: false,
                    vote_average: 6.3,
                    vote_count: 1179,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 974169,
                known_for_department: 'Acting',
                name: 'Jenna Ortega',
                original_name: 'Jenna Ortega',
                popularity: 144.449,
                profile_path: '/q1NRzyZQlYkxLY07GO9NVPkQnu8.jpg',
                known_for: [
                  {
                    backdrop_path: '/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
                    id: 119051,
                    name: 'Wednesday',
                    original_name: 'Wednesday',
                    overview:
                      'Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.',
                    poster_path: '/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [10765, 9648, 35],
                    popularity: 214.399,
                    first_air_date: '2022-11-23',
                    vote_average: 8.456,
                    vote_count: 8610,
                    origin_country: ['US'],
                  },
                  {
                    backdrop_path: '/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg',
                    id: 646385,
                    title: 'Scream',
                    original_title: 'Scream',
                    overview:
                      'Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.',
                    poster_path: '/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [27, 9648, 53],
                    popularity: 158.401,
                    release_date: '2022-01-12',
                    video: false,
                    vote_average: 6.7,
                    vote_count: 3260,
                  },
                  {
                    backdrop_path: '/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg',
                    id: 760104,
                    title: 'X',
                    original_title: 'X',
                    overview:
                      'In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.',
                    poster_path: '/A7YPhQKdcr6XB1kCUdS4tHifYWd.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [27, 9648, 53],
                    popularity: 88.527,
                    release_date: '2022-03-17',
                    video: false,
                    vote_average: 6.8,
                    vote_count: 3191,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 4095744,
                known_for_department: 'Acting',
                name: 'Dyessa Garcia',
                original_name: 'Dyessa Garcia',
                popularity: 141.672,
                profile_path: '/xak9L0fkIOkjSwJpz3SWLl94tVP.jpg',
                known_for: [
                  {
                    backdrop_path: '/uUJuPiZh1QfIeTa1GeLWqnEkaP2.jpg',
                    id: 1302011,
                    title: 'Init',
                    original_title: 'Init',
                    overview:
                      'When a young barrio lass moves in to the city to study, she lives in a boarding house with other college students. Unknown to them, behind her shy and timid personality is a woman with insatiable hunger for sex.',
                    poster_path: '/fGY13rtdRzFqTkDMi5JayUWg6vL.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [18],
                    popularity: 38.438,
                    release_date: '2024-07-30',
                    video: false,
                    vote_average: 5.0,
                    vote_count: 4,
                  },
                  {
                    backdrop_path: '/4GHPT4glMQHPCke2DNigRqZ6KqH.jpg',
                    id: 1226299,
                    title: 'Dilig',
                    original_title: 'Dilig',
                    overview:
                      'About to get married to an old, wealthy businessman, Resa enlists the help of gardener Otso to seduce her fiancé’s daughter, Katelyn, and record his sexploits with her in order to get her disowned.',
                    poster_path: '/lDn02aAZFUb7JpM7l7iuHdbWEHH.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [18],
                    popularity: 29.244,
                    release_date: '2024-01-30',
                    video: false,
                    vote_average: 3.5,
                    vote_count: 2,
                  },
                  {
                    backdrop_path: '/cosfYxYz3BvENZTxyiWORjX4Ghf.jpg',
                    id: 1262596,
                    title: 'Sweet Release',
                    original_title: 'Sweet Release',
                    overview:
                      'Ataska and Dyessa Garcia will take you to a hot and crazy roadtrip perfect for the summer season. Two girl bestfriends and a young man take on a a journey of self-discovery. Along the way, their bond deepens as they explore their sexual desires.',
                    poster_path: '/blp7kKUbGSNPJyYYHalYEL4n7t1.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [18],
                    popularity: 45.658,
                    release_date: '2024-04-12',
                    video: false,
                    vote_average: 3.9,
                    vote_count: 4,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 224513,
                known_for_department: 'Acting',
                name: 'Ana de Armas',
                original_name: 'Ana de Armas',
                popularity: 140.157,
                profile_path: '/3vxvsmYLTf4jnr163SUlBIw51ee.jpg',
                known_for: [
                  {
                    backdrop_path: '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg',
                    id: 335984,
                    title: 'Blade Runner 2049',
                    original_title: 'Blade Runner 2049',
                    overview:
                      "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
                    poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [878, 18],
                    popularity: 116.497,
                    release_date: '2017-10-04',
                    video: false,
                    vote_average: 7.6,
                    vote_count: 13544,
                  },
                  {
                    backdrop_path: '/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg',
                    id: 546554,
                    title: 'Knives Out',
                    original_title: 'Knives Out',
                    overview:
                      "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
                    poster_path: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [35, 80, 9648],
                    popularity: 69.6,
                    release_date: '2019-11-27',
                    video: false,
                    vote_average: 7.8,
                    vote_count: 12284,
                  },
                  {
                    backdrop_path: '/oNoprEND25zXR6Fns8cIZUkuoMc.jpg',
                    id: 308266,
                    title: 'War Dogs',
                    original_title: 'War Dogs',
                    overview:
                      "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
                    poster_path: '/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [35, 80, 18],
                    popularity: 33.616,
                    release_date: '2016-08-18',
                    video: false,
                    vote_average: 6.922,
                    vote_count: 4863,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 1245,
                known_for_department: 'Acting',
                name: 'Scarlett Johansson',
                original_name: 'Scarlett Johansson',
                popularity: 138.791,
                profile_path: '/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg',
                known_for: [
                  {
                    backdrop_path: '/ozVwXlfxqNsariipatGwa5px3Pm.jpg',
                    id: 240832,
                    title: 'Lucy',
                    original_title: 'Lucy',
                    overview:
                      'A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.',
                    poster_path: '/kRbpUTRNm6QbLQFPFWUcNC4czEm.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 878],
                    popularity: 77.232,
                    release_date: '2014-07-25',
                    video: false,
                    vote_average: 6.453,
                    vote_count: 15909,
                  },
                  {
                    backdrop_path: '/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg',
                    id: 497698,
                    title: 'Black Widow',
                    original_title: 'Black Widow',
                    overview:
                      'Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.',
                    poster_path: '/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 12, 878],
                    popularity: 74.721,
                    release_date: '2021-01-01',
                    video: false,
                    vote_average: 7.233,
                    vote_count: 10120,
                  },
                  {
                    backdrop_path: '/7lINTRMapEkgQbwYfAYX3178xRf.jpg',
                    id: 315837,
                    title: 'Ghost in the Shell',
                    original_title: 'Ghost in the Shell',
                    overview:
                      "In the near future, Major is the first of her kind: a human saved from a terrible crash, then cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.",
                    poster_path: '/myRzRzCxdfUWjkJWgpHHZ1oGkJd.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [878, 18, 28],
                    popularity: 44.596,
                    release_date: '2017-03-29',
                    video: false,
                    vote_average: 6.1,
                    vote_count: 7942,
                  },
                ],
              },
              {
                adult: false,
                gender: 3,
                id: 1982141,
                known_for_department: 'Acting',
                name: 'Jess Chanliau',
                original_name: 'Jess Chanliau',
                popularity: 133.249,
                profile_path: '/wx0GIkCqrqt1Vg4SIM63ipbuyZT.jpg',
                known_for: [
                  {
                    backdrop_path: '/e7k3Gbeq7TjFP22AOzDI7kVwaUE.jpg',
                    id: 523371,
                    title: 'Inmate Zero',
                    original_title: 'Patients of a Saint',
                    overview:
                      "There's a zombie outbreak after a medical trial in an international detention and medical facility on an isolated island. An ex US Special Forces/bodyguard woman inmate and a guard form a team.",
                    poster_path: '/pf6izZGF8HQvGHUu55SeVn0PJTD.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [27],
                    popularity: 7.477,
                    release_date: '2020-02-28',
                    video: false,
                    vote_average: 6.4,
                    vote_count: 118,
                  },
                  {
                    backdrop_path: '/v6f9FUDDQfGIv8MLRQwlL0zvRjI.jpg',
                    id: 203857,
                    name: 'The Diplomat',
                    original_name: 'The Diplomat',
                    overview:
                      'In the midst of an international crisis, a career diplomat lands in a high-profile job she’s unsuited for, with tectonic implications for her marriage and her political future.',
                    poster_path: '/cOKXV0FalCYixNmZYCfHXgyQ0VX.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [18, 10768],
                    popularity: 277.54,
                    first_air_date: '2023-04-20',
                    vote_average: 7.4,
                    vote_count: 217,
                    origin_country: ['US'],
                  },
                  {
                    backdrop_path: '/imJuFvz6WJZS9vBywm0vPYYL42K.jpg',
                    id: 93289,
                    name: 'Brave New World',
                    original_name: 'Brave New World',
                    overview:
                      'In a utopia whose perfection hinges upon control of monogamy and privacy, members of the collective begin to question the rules, putting their regimented society on a collision course with forbidden love and revolution.',
                    poster_path: '/vPl7hAY0vt0OPhIflRb5IXrssBv.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [10765, 18],
                    popularity: 21.234,
                    first_air_date: '2020-07-15',
                    vote_average: 6.7,
                    vote_count: 183,
                    origin_country: ['US'],
                  },
                ],
              },
              {
                adult: false,
                gender: 2,
                id: 976,
                known_for_department: 'Acting',
                name: 'Jason Statham',
                original_name: 'Jason Statham',
                popularity: 129.904,
                profile_path: '/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg',
                known_for: [
                  {
                    backdrop_path: '/6bAjogOzrB9xbmIaY3BRpZZgn5Q.jpg',
                    id: 345940,
                    title: 'The Meg',
                    original_title: 'The Meg',
                    overview:
                      'A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.',
                    poster_path: '/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 878, 27],
                    popularity: 52.497,
                    release_date: '2018-08-09',
                    video: false,
                    vote_average: 6.253,
                    vote_count: 7586,
                  },
                  {
                    backdrop_path: '/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg',
                    id: 4108,
                    title: 'The Transporter',
                    original_title: 'The Transporter',
                    overview:
                      'Former Special Forces officer Frank Martin will deliver anything to anyone for the right price, and his no-questions-asked policy puts him in high demand. But when he realizes his latest cargo is alive, it sets in motion a dangerous chain of events. The bound and gagged Lai is being smuggled to France by a shady American businessman, and Frank works to save her as his own illegal activities are uncovered by a French detective.',
                    poster_path: '/v3QIFUWgtVN4wejVuDZowuyJ20W.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 80, 53],
                    popularity: 34.305,
                    release_date: '2002-10-02',
                    video: false,
                    vote_average: 6.711,
                    vote_count: 5274,
                  },
                  {
                    backdrop_path: '/70AV2Xx5FQYj20labp0EGdbjI6E.jpg',
                    id: 637649,
                    title: 'Wrath of Man',
                    original_title: 'Wrath of Man',
                    overview:
                      "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
                    poster_path: '/M7SUK85sKjaStg4TKhlAVyGlz3.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [80, 28, 53],
                    popularity: 102.539,
                    release_date: '2021-04-22',
                    video: false,
                    vote_average: 7.631,
                    vote_count: 5222,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 572043,
                known_for_department: 'Acting',
                name: 'Yang Mi',
                original_name: '杨幂',
                popularity: 124.599,
                profile_path: '/6RezRxlQBsYmlotybR3q7riSrvV.jpg',
                known_for: [
                  {
                    backdrop_path: '/tkuVd1LYyltRdiWO50kJ5lc4J9V.jpg',
                    id: 611698,
                    title: "A Writer's Odyssey",
                    original_title: '刺杀小说家',
                    overview:
                      'Kongwen Lu is the author of a fantasy novel series following a heroic teenager, also named Kongwen, on a quest to end the tyrannical rule of Lord Redmane, under the guidance of a Black Armor. But through a strange twist of fate, the fantasy world of the novel begins to impact life in the real world, leading Guan Ning to accept a mission from Tu Ling to kill the author.',
                    poster_path: '/7hEhhmAF8Tr7g95fkbuxDpeR27b.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'zh',
                    genre_ids: [14, 28, 12, 18],
                    popularity: 43.875,
                    release_date: '2021-02-12',
                    video: false,
                    vote_average: 7.138,
                    vote_count: 294,
                  },
                  {
                    backdrop_path: '/lKilKeX1rlIhRcY4xQPP4bmuct9.jpg',
                    id: 369552,
                    title: 'L.O.R.D: Legend of Ravaging Dynasties',
                    original_title: '爵迹',
                    overview:
                      'Based on the novel of the same name, the film depicts the endless battles of four kingdoms as they fight for power and domination of the one ultimate realm.Based on his 2 beloved fantasy novels with 6 million copies sold, L.O.R.D is acclaimed writer and director Guo Jingming’s follow up to his Tiny Times films.  The action-adventure odyssey is set in a world of warring Sorcerers, Lords and Beasts. The first CGI Film to come from China',
                    poster_path: '/qIUDi1XDAREkarkwNzOOBgUzqyC.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'zh',
                    genre_ids: [16, 14, 18, 878],
                    popularity: 8.187,
                    release_date: '2016-09-29',
                    video: false,
                    vote_average: 7.0,
                    vote_count: 130,
                  },
                  {
                    backdrop_path: '/f2fWG89GPSe31ymp6pqJANfjbit.jpg',
                    id: 457832,
                    title: 'Reset',
                    original_title: '逆时营救',
                    overview:
                      'In 2025, a scientist on the verge of making a major discovery related to time travel is suddenly put in peril when a rival kidnaps her young son and demands a hefty ransom: her entire research.',
                    poster_path: '/zwTonDtQstoMQHYEBCz8x8RvBJJ.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'zh',
                    genre_ids: [28, 878],
                    popularity: 7.075,
                    release_date: '2017-06-28',
                    video: false,
                    vote_average: 7.0,
                    vote_count: 101,
                  },
                ],
              },
              {
                adult: false,
                gender: 2,
                id: 6384,
                known_for_department: 'Acting',
                name: 'Keanu Reeves',
                original_name: 'Keanu Reeves',
                popularity: 123.166,
                profile_path: '/4D0PpNI0kmP58hgrwGC3wCjxhnm.jpg',
                known_for: [
                  {
                    backdrop_path: '/icmmSD4vTTDKOq2vvdulafOGw93.jpg',
                    id: 603,
                    title: 'The Matrix',
                    original_title: 'The Matrix',
                    overview:
                      'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
                    poster_path: '/p96dm7sCMn4VYAStA6siNz30G1r.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 878],
                    popularity: 127.284,
                    release_date: '1999-03-31',
                    video: false,
                    vote_average: 8.2,
                    vote_count: 25553,
                  },
                  {
                    backdrop_path: '/ipyxbPJrLB1g9AfHq4xH5nLWmew.jpg',
                    id: 245891,
                    title: 'John Wick',
                    original_title: 'John Wick',
                    overview:
                      'Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.',
                    poster_path: '/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 53],
                    popularity: 58.379,
                    release_date: '2014-10-22',
                    video: false,
                    vote_average: 7.438,
                    vote_count: 19079,
                  },
                  {
                    backdrop_path: '/tHkujDqdPC9VQoFpEWU0QgWIZyM.jpg',
                    id: 324552,
                    title: 'John Wick: Chapter 2',
                    original_title: 'John Wick: Chapter 2',
                    overview:
                      'John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.',
                    poster_path: '/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 53, 80],
                    popularity: 69.888,
                    release_date: '2017-02-08',
                    video: false,
                    vote_average: 7.334,
                    vote_count: 12952,
                  },
                ],
              },
              {
                adult: false,
                gender: 2,
                id: 2524,
                known_for_department: 'Acting',
                name: 'Tom Hardy',
                original_name: 'Tom Hardy',
                popularity: 122.581,
                profile_path: '/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg',
                known_for: [
                  {
                    backdrop_path: '/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg',
                    id: 76341,
                    title: 'Mad Max: Fury Road',
                    original_title: 'Mad Max: Fury Road',
                    overview:
                      'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.',
                    poster_path: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 12, 878],
                    popularity: 131.168,
                    release_date: '2015-05-13',
                    video: false,
                    vote_average: 7.615,
                    vote_count: 22501,
                  },
                  {
                    backdrop_path: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
                    id: 335983,
                    title: 'Venom',
                    original_title: 'Venom',
                    overview:
                      'Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.',
                    poster_path: '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [878, 28],
                    popularity: 2018.088,
                    release_date: '2018-09-28',
                    video: false,
                    vote_average: 6.8,
                    vote_count: 15849,
                  },
                  {
                    backdrop_path: '/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg',
                    id: 580489,
                    title: 'Venom: Let There Be Carnage',
                    original_title: 'Venom: Let There Be Carnage',
                    overview:
                      'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
                    poster_path: '/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [878, 28, 12],
                    popularity: 1619.971,
                    release_date: '2021-09-30',
                    video: false,
                    vote_average: 6.799,
                    vote_count: 10081,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 3371804,
                known_for_department: 'Acting',
                name: 'Christine Bermas',
                original_name: 'Christine Bermas',
                popularity: 120.327,
                profile_path: '/zdFbplqeZbzgCJEJfnj1pPqVVH2.jpg',
                known_for: [
                  {
                    backdrop_path: '/zGkUjZNz7yhbPcCgVtrO24GvpLJ.jpg',
                    id: 990485,
                    title: 'Scorpio Nights 3',
                    original_title: 'Scorpio Nights 3',
                    overview:
                      "A young couple's sex acts are witnessed by a young man through a hole. When the wife seduces him, they engage in an illicit affair. Chaos ensues when the husband learns about them.",
                    poster_path: '/9uBbhfM8Co57T4Fn5flo0tMn5NC.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [53],
                    popularity: 36.854,
                    release_date: '2022-07-28',
                    video: false,
                    vote_average: 6.3,
                    vote_count: 12,
                  },
                  {
                    backdrop_path: '/cgvio9pxvmvaRDMucIY0gldxPdj.jpg',
                    id: 949983,
                    title: 'Island of Desire',
                    original_title: 'Island of Desire',
                    overview:
                      "A nurse is assigned to work at an island called Isla Bato, where men treat women with lust. As she experiences the people's madness, she plans a way to get out of the island.",
                    poster_path: '/aGT1dS0CvHuD1Bu2K5Ameh4mRjl.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [18, 53],
                    popularity: 16.142,
                    release_date: '2022-04-01',
                    video: false,
                    vote_average: 4.4,
                    vote_count: 10,
                  },
                  {
                    backdrop_path: '/72EdK1xuE7a6q8tB3uUaxAuk60d.jpg',
                    id: 1209770,
                    title: 'Bedspacer',
                    original_title: 'Bedspacer',
                    overview:
                      "Janice's steamy obsession to imitate Lexi propels them to campus stardom. But dark secrets blur the lines between authenticity and seductive deception.",
                    poster_path: '/5LJ9V0KBPwdV0uflsddMrX4Ll3v.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [53, 18],
                    popularity: 56.844,
                    release_date: '2024-01-05',
                    video: false,
                    vote_average: 3.9,
                    vote_count: 8,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 54882,
                known_for_department: 'Acting',
                name: 'Morena Baccarin',
                original_name: 'Morena Baccarin',
                popularity: 109.098,
                profile_path: '/kBSKKaOtsqIzZPhtEeHfCBmhWl9.jpg',
                known_for: [
                  {
                    backdrop_path: '/en971MEXui9diirXlogOrPKmsEn.jpg',
                    id: 293660,
                    title: 'Deadpool',
                    original_title: 'Deadpool',
                    overview:
                      'The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.',
                    poster_path: '/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 12, 35],
                    popularity: 137.937,
                    release_date: '2016-02-09',
                    video: false,
                    vote_average: 7.623,
                    vote_count: 30909,
                  },
                  {
                    backdrop_path: '/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg',
                    id: 383498,
                    title: 'Deadpool 2',
                    original_title: 'Deadpool 2',
                    overview:
                      "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
                    poster_path: '/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 35, 12],
                    popularity: 89.26,
                    release_date: '2018-05-10',
                    video: false,
                    vote_average: 7.5,
                    vote_count: 17840,
                  },
                  {
                    backdrop_path: '/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg',
                    id: 524047,
                    title: 'Greenland',
                    original_title: 'Greenland',
                    overview:
                      'John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garritys experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.',
                    poster_path: '/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 53, 18],
                    popularity: 57.812,
                    release_date: '2020-07-29',
                    video: false,
                    vote_average: 7.1,
                    vote_count: 4480,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 3775928,
                known_for_department: 'Acting',
                name: 'Julia Victoria',
                original_name: 'Julia Victoria',
                popularity: 108.047,
                profile_path: '/3Xm4zDO3gUVU4OWZnhb983GnEGx.jpg',
                known_for: [
                  {
                    backdrop_path: '/oKtYeBnasbOoJvEUgUVW6xdKpM7.jpg',
                    id: 1127209,
                    title: 'Kabayo',
                    original_title: 'Kabayo',
                    overview:
                      'A story about Laurene who wants to elevate her seven-year relationship with Conrad. When Easton comes inito the picture, she believes she is the perfect addition to their sexual relationship.',
                    poster_path: '/uhBScHjoMlrWUhsm5vPIBNvksKY.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [18],
                    popularity: 35.18,
                    release_date: '2023-05-26',
                    video: false,
                    vote_average: 2.3,
                    vote_count: 3,
                  },
                  {
                    backdrop_path: '/fcAMgGvNNu3xWiBHczzI0aZt7Pf.jpg',
                    id: 214080,
                    name: 'Lovely Ladies Dormitory',
                    original_name: 'Lovely Ladies Dormitory',
                    overview:
                      'Five modern women live together in one roof as they deal with their families, career, and men and explore their colorful sex lives.',
                    poster_path: '/1aFfOosjyt6169qnZTSgnhRqPCf.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [18],
                    popularity: 47.522,
                    first_air_date: '2022-12-18',
                    vote_average: 4.4,
                    vote_count: 7,
                    origin_country: ['PH'],
                  },
                  {
                    backdrop_path: '/eLpqvYFtnqHjPwV0B0p1jpt0rXP.jpg',
                    id: 1076607,
                    title: 'Lawa',
                    original_title: 'Lawa',
                    overview:
                      "A young videographer uses his camera to capture intimate moment of lovers visiting a beautiful and peaceful lake. He uses the captured videos for his own benefit of earning cash. It's just a matter of time until his dark practice will be revealed and dealt with accordingly.",
                    poster_path: '/4nIzQWkte1RA56y4XTWE8UGdmDB.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'tl',
                    genre_ids: [53],
                    popularity: 8.099,
                    release_date: '2023-03-03',
                    video: false,
                    vote_average: 3.0,
                    vote_count: 5,
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 2049994,
                known_for_department: 'Acting',
                name: 'Zhao Lusi',
                original_name: '赵露思',
                popularity: 107.574,
                profile_path: '/edHYkTOynX6sBe82ToIJdlG22hu.jpg',
                known_for: [
                  {
                    backdrop_path: '/wQlJJJ50gKphCci0SmoetUXmJN4.jpg',
                    id: 210733,
                    name: 'Hidden Love',
                    original_name: '偷偷藏不住',
                    overview:
                      'Since high school, Sang Zhi has had a crush on Duan Jiaxu. When fate brings them together again, they find a chance to embark on a sweet relationship.',
                    poster_path: '/riGzESa9N9toumP9OhMmg0QvFPD.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'zh',
                    genre_ids: [18],
                    popularity: 117.737,
                    first_air_date: '2023-06-20',
                    vote_average: 8.491,
                    vote_count: 106,
                    origin_country: ['CN'],
                  },
                  {
                    backdrop_path: '/5BuVAlwQiLHVqTWITHxaLmp2leB.jpg',
                    id: 87299,
                    name: 'I Hear You',
                    original_name: '最动听的事',
                    overview:
                      'Bei Er Duo, a girl from an ordinary family, dreams about studying in Japan to be a professional voice actor. However, her mother wants her to marry rich whilst she is young, leading to continuous blind dates which irritate Bei Er Duo. In her desperation to raise funds for studying overseas as well as helping her best friend Tang Li out of a crisis, Bei Er Duo joins a couple reality program, encountering top violin maker Ye Shu Wei.',
                    poster_path: '/2wVMh3vqvt1IgAhextxwUKxaOAH.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'zh',
                    genre_ids: [18],
                    popularity: 22.401,
                    first_air_date: '2019-01-28',
                    vote_average: 7.6,
                    vote_count: 65,
                    origin_country: ['CN'],
                  },
                  {
                    backdrop_path: '/gxafmR8O7cAJxmrs3RHp1P2ftsY.jpg',
                    id: 103635,
                    name: 'The Romance of Tiger and Rose',
                    original_name: '传闻中的陈芊芊',
                    overview:
                      "A screenwriter finds herself becoming a character in the script of her own creation. However, she is not meant to live past three episodes! Chen Xiaoqian is a writer who poured blood, sweat and tears into creating a big female-centric drama. What could have started filming smoothly quickly turned south because of actor Han Mingxing's reservations about the script. Feeling wronged, Chen Xiaoqian vows to prove herself yet she accidentally gets stuck in a parallel world where her story has come to life. Now known as the 3rd princess Chen Qianqian, she is an insignificant side character with a horrid reputation that is not meant to live long in the story. In order to live, she starts on a road to reverse her fate. She also gets caught in between the arrogant and black-bellied prince Han Shuo and the practically perfect Pei Heng.",
                    poster_path: '/mCsidkxf6ji8e71T07dYff3FjCF.jpg',
                    media_type: 'tv',
                    adult: false,
                    original_language: 'zh',
                    genre_ids: [35, 18],
                    popularity: 25.947,
                    first_air_date: '2020-05-18',
                    vote_average: 7.4,
                    vote_count: 22,
                    origin_country: ['CN'],
                  },
                ],
              },
              {
                adult: false,
                gender: 1,
                id: 3967,
                known_for_department: 'Acting',
                name: 'Kate Beckinsale',
                original_name: 'Kate Beckinsale',
                popularity: 101.14,
                profile_path: '/9RnPZhX9PXaHL4PFE65RUQLSewt.jpg',
                known_for: [
                  {
                    backdrop_path: '/cAq6sMPAyUcpjS1icjyp4Eiz2S8.jpg',
                    id: 277,
                    title: 'Underworld',
                    original_title: 'Underworld',
                    overview:
                      "Vampires and werewolves have waged a nocturnal war against each other for centuries. But all bets are off when a female vampire warrior named Selene, who's famous for her strength and werewolf-hunting prowess, becomes smitten with a peace-loving male werewolf, Michael, who wants to end the war.",
                    poster_path: '/zsnQ41UZ3jo1wEeemF0eA9cAIU0.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [14, 28, 53],
                    popularity: 41.81,
                    release_date: '2003-09-19',
                    video: false,
                    vote_average: 6.8,
                    vote_count: 6062,
                  },
                  {
                    backdrop_path: '/wJJJS5ey53DqJ3cTuu7GFJsRsWu.jpg',
                    id: 52520,
                    title: 'Underworld: Awakening',
                    original_title: 'Underworld: Awakening',
                    overview:
                      "Having escaped years of imprisonment, vampire warrioress Selene finds herself in a changed world where humans have discovered the existence of both Vampire and Lycan clans and are conducting an all-out war to eradicate both immortal species. Now Selene must battle the humans and a frightening new breed of super Lycans to ensure the death dealers' survival.",
                    poster_path: '/jN0uuc8U6M3sTg9zEaliJV60Stf.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [14, 28, 27],
                    popularity: 33.114,
                    release_date: '2012-01-19',
                    video: false,
                    vote_average: 6.3,
                    vote_count: 4024,
                  },
                  {
                    backdrop_path: '/kIZzOU6ZSbcyejTK0c5BBeF3YfD.jpg',
                    id: 834,
                    title: 'Underworld: Evolution',
                    original_title: 'Underworld: Evolution',
                    overview:
                      'As the war between the vampires and the Lycans rages on, Selene, a former member of the Death Dealers (an elite vampire special forces unit that hunts werewolves), and Michael, the werewolf hybrid, work together in an effort to unlock the secrets of their respective bloodlines.',
                    poster_path: '/yT1EDKhCzAumcZeBoAxqm0nY2H8.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [14, 28, 53],
                    popularity: 27.451,
                    release_date: '2006-01-12',
                    video: false,
                    vote_average: 6.6,
                    vote_count: 3971,
                  },
                ],
              },
              {
                adult: false,
                gender: 2,
                id: 500,
                known_for_department: 'Acting',
                name: 'Tom Cruise',
                original_name: 'Tom Cruise',
                popularity: 100.195,
                profile_path: '/3mShHjSQR7NXOVbdTu5rT2Qd0MN.jpg',
                known_for: [
                  {
                    backdrop_path: '/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg',
                    id: 137113,
                    title: 'Edge of Tomorrow',
                    original_title: 'Edge of Tomorrow',
                    overview:
                      'Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.',
                    poster_path: '/xjw5trHV7Mwo61P0kCTy8paEkgO.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 878],
                    popularity: 76.289,
                    release_date: '2014-05-27',
                    video: false,
                    vote_average: 7.625,
                    vote_count: 13734,
                  },
                  {
                    backdrop_path: '/A6wFgFFEgymebp518fcsa71jnSu.jpg',
                    id: 75612,
                    title: 'Oblivion',
                    original_title: 'Oblivion',
                    overview:
                      'Jack Harper is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete. His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft. Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.',
                    poster_path: '/eO3r38fwnhb58M1YgcjQBd3VNcp.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 878, 12, 9648],
                    popularity: 28.972,
                    release_date: '2013-04-10',
                    video: false,
                    vote_average: 6.645,
                    vote_count: 10588,
                  },
                  {
                    backdrop_path: '/ih4lZkUpmSE7AP3maymiO72xJ1z.jpg',
                    id: 56292,
                    title: 'Mission: Impossible - Ghost Protocol',
                    original_title: 'Mission: Impossible - Ghost Protocol',
                    overview:
                      'Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.',
                    poster_path: '/eRZTGx7GsiKqPch96k27LK005ZL.jpg',
                    media_type: 'movie',
                    adult: false,
                    original_language: 'en',
                    genre_ids: [28, 53, 12],
                    popularity: 57.658,
                    release_date: '2011-12-07',
                    video: false,
                    vote_average: 7.1,
                    vote_count: 9801,
                  },
                ],
              },
            ],
            total_pages: 184798,
            total_results: 3695955,
          });
        }),
      ],
    },
  },
};

export default meta;
type Story = StoryObj<typeof IndexPage>;

export const Primary: Story = {};
